version: "3.4"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./data/mysql:/data/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
